# Generated by Django 5.0.8 on 2025-03-27 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[],
        ),
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="users/avatars/%Y/%m/%d",
                verbose_name="Avatar",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, verbose_name="Bio"),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Date of birth"
            ),
        ),
    ]
