# Generated by Django 5.0.8 on 2025-03-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_managers_alter_user_avatar_alter_user_bio_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_social_user",
            field=models.BooleanField(default=False, verbose_name="Is social user"),
        ),
    ]
