# Generated by Django 5.0.8 on 2025-03-24 19:45

import apps.kinogo.models.movie
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Actor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Actor",
                "verbose_name_plural": "Actors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categorys",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Director",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Director",
                "verbose_name_plural": "Directors",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Episode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="movies/episodes/%Y/%m/%d",
                        verbose_name="Episode thumbnail",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Episode number")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                ("duration", models.DurationField(verbose_name="Duration")),
                (
                    "video_file",
                    models.FileField(
                        upload_to="movies/episodes/%Y/%m/%d",
                        verbose_name="Episode file",
                    ),
                ),
                (
                    "release_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Release date"
                    ),
                ),
                (
                    "alt_sources",
                    models.JSONField(
                        blank=True, null=True, verbose_name="Alternative sources"
                    ),
                ),
            ],
            options={
                "verbose_name": "Episode",
                "verbose_name_plural": "Episodes",
            },
        ),
        migrations.CreateModel(
            name="Genre",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    models.CharField(max_length=255, unique=True, verbose_name="Name"),
                ),
            ],
            options={
                "verbose_name": "Genre",
                "verbose_name_plural": "Genres",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MovieDislikes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Movie Like",
                "verbose_name_plural": "Movie Dislikes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MovieLikes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Movie Like",
                "verbose_name_plural": "Movie Likes",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MovieRating",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MaxValueValidator(1),
                            django.core.validators.MinValueValidator(5),
                        ],
                        verbose_name="Rating",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie Rating",
                "verbose_name_plural": "Movie Ratings",
            },
        ),
        migrations.CreateModel(
            name="MovieTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie Tag",
                "verbose_name_plural": "Movie Tags",
            },
        ),
        migrations.CreateModel(
            name="Season",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="movies/seasons/%Y/%m/%d",
                        verbose_name="Season poster",
                    ),
                ),
                ("number", models.PositiveIntegerField(verbose_name="Season number")),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Title"
                    ),
                ),
            ],
            options={
                "verbose_name": "Season",
                "verbose_name_plural": "Seasons",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255, verbose_name="Name")),
            ],
            options={
                "verbose_name": "Tag",
                "verbose_name_plural": "Tags",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WatchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Watch History",
                "verbose_name_plural": "Watch Histories",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Movie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=255, verbose_name="Title")),
                ("slug", models.SlugField(blank=True, unique=True)),
                (
                    "banner",
                    models.ImageField(
                        upload_to="movies/%Y/%m/%d", verbose_name="Banner"
                    ),
                ),
                (
                    "video_file",
                    models.FileField(upload_to="movies/%Y/%m/%d", verbose_name="Movie"),
                ),
                (
                    "trailer_url",
                    models.URLField(blank=True, null=True, verbose_name="Trailer URL"),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Description"),
                ),
                (
                    "year_of_release",
                    models.IntegerField(
                        blank=True,
                        null=True,
                        validators=[apps.kinogo.models.movie.validate_year],
                        verbose_name="Year of relase",
                    ),
                ),
                ("world_premiere", models.DateField(blank=True, null=True)),
                ("country", models.CharField(max_length=100, verbose_name="Country")),
                (
                    "views_count",
                    models.PositiveIntegerField(default=0, verbose_name="Views count"),
                ),
                (
                    "duration",
                    models.DurationField(
                        blank=True, null=True, verbose_name="Duration"
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="Language"
                    ),
                ),
                (
                    "subtitles",
                    models.JSONField(blank=True, null=True, verbose_name="Subtitles"),
                ),
                (
                    "movie_type",
                    models.CharField(
                        choices=[
                            ("movie", "Movie"),
                            ("series", "Series"),
                            ("mini_series", "Mini Series"),
                            ("documentary", "Documentary"),
                        ],
                        default="movie",
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                (
                    "actors",
                    models.ManyToManyField(related_name="movies", to="kinogo.actor"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="kinogo.category",
                    ),
                ),
                (
                    "director",
                    models.ManyToManyField(related_name="movies", to="kinogo.director"),
                ),
                (
                    "genre",
                    models.ManyToManyField(related_name="movies", to="kinogo.genre"),
                ),
            ],
            options={
                "verbose_name": "Movie",
                "verbose_name_plural": "Movies",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MovieComment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("message", models.TextField(verbose_name="Message")),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movie_comments",
                        to="kinogo.movie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Movie Comment",
                "verbose_name_plural": "Movie Comments",
                "ordering": ["-created_at"],
            },
        ),
    ]
