# Generated by Django 5.0.8 on 2025-03-24 19:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("kinogo", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="moviecomment",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_comments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="moviedislikes",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_dislikes",
                to="kinogo.movie",
            ),
        ),
        migrations.AddField(
            model_name="moviedislikes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_dislikes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movielikes",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_likes",
                to="kinogo.movie",
            ),
        ),
        migrations.AddField(
            model_name="movielikes",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_likes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movierating",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_ratings",
                to="kinogo.movie",
            ),
        ),
        migrations.AddField(
            model_name="movierating",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_ratings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="movietag",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_tags",
                to="kinogo.movie",
            ),
        ),
        migrations.AddField(
            model_name="season",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="seasons",
                to="kinogo.movie",
            ),
        ),
        migrations.AddField(
            model_name="episode",
            name="season",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="episodes",
                to="kinogo.season",
            ),
        ),
        migrations.AddField(
            model_name="movietag",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movie_tags",
                to="kinogo.tag",
            ),
        ),
        migrations.AddField(
            model_name="watchhistory",
            name="movie",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watch_histories",
                to="kinogo.movie",
            ),
        ),
        migrations.AddField(
            model_name="watchhistory",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="watch_histories",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="moviedislikes",
            unique_together={("user", "movie")},
        ),
        migrations.AlterUniqueTogether(
            name="movielikes",
            unique_together={("user", "movie")},
        ),
        migrations.AlterUniqueTogether(
            name="movierating",
            unique_together={("user", "movie")},
        ),
        migrations.AlterUniqueTogether(
            name="season",
            unique_together={("movie", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="episode",
            unique_together={("season", "number")},
        ),
        migrations.AlterUniqueTogether(
            name="watchhistory",
            unique_together={("user", "movie")},
        ),
    ]
