# Generated by Django 5.0.8 on 2025-03-25 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("kinogo", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="movie",
            old_name="director",
            new_name="directors",
        ),
        migrations.RenameField(
            model_name="movie",
            old_name="genre",
            new_name="genres",
        ),
    ]
