# Generated by Django 5.0.8 on 2025-03-26 08:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kinogo", "0004_alter_movie_actors_alter_movie_country_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movierating",
            name="rating",
            field=models.IntegerField(
                default=0,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(5),
                ],
                verbose_name="Rating",
            ),
        ),
    ]
